const string = `Jake is smart; true;
The Earth is Flat; false;
Jake can't not roste; false;
Working in this class is helps; true;
Pluto is not a normal planet; true;
Global warming isnt real; false;
bowen is not not not not not not smart; true;
Jake is a good driver; true;
The sun is hot; true;
Aidan is not lazy; fase;
when working with Aidan litle work gets done; true;
Mike isnt a total beast with monty in r6s; false;
piggins were made by the government; false;
bad dragon is a comoto dragon breeding company with the goal of making them a domesticated pet; true;
The earth is not flat; true;
The earth is not a perfect sphere; true;
Radiation kills; true;
Mike can spell much good; false;
global warming is bad; true;
memphis is kim john un; true;
fire herts; true;
aidan is bad at siege; false;
memphis is secretly tall but has prosthetic legs; true;
Aidan noob rages on rainbow 6 siege (and sucks at it); true;
euan is memphis's twin and took his legs; true;
it smells like stale diretos; true;
Emma is tall; false;
it is raining outside; true;
Aidan is an idiot; false;
Bowen is cool; true;
Memphis cant reach the top shelf; false;
lamorie has baby legs; false;
bowen has aidans wallet;
Mike cant spell refrigir8tors; false;
mr malorie secretly works for nasa; true;
jake has a shark neckless; true;
jake like pizza; true;
it is still summer; false;
jakes computer is a dcu; false;
aidan has a youtube channel called blaze conroy; true;
sharks have arms; false;
Bowen doesnt have glasses; true;
kade has a crush on brad; true;
euan is swim; true;
mike is trash; true;
aidan is the better leader; false;
aidan has a future; true;
TBB is best; true;
Lamorie is cool; true;
mike is here legaly; false
alienwear is a good brand; true;
the sky is blue; true;
Lamorie has baby legs; true;
Jake is a noob; true;
PC masterace; true;
jake is a good driver; false;
Mike is not a squeaker; true;
aidan has a wallet; false;
gaming laptops are good; false;
mike can do basic motor functions; false
siege has small maps; true;
mike is cool; false;`
